from enum import Enum


class VerificationStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    REVIEW = "REVIEW"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class DecisionEnum(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    VERIFIED = "VERIFIED"
    FLAGGED = "FLAGGED"
    FAILED = "FAILED"


class VerificationRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    OCR = "OCR"
    EXTRACTING = "EXTRACTING"
    VERIFYING = "VERIFYING"
    RULE_EVALUATION = "RULE_EVALUATION"
    SCORING = "SCORING"
    AI_ANALYSIS = "AI_ANALYSIS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DocumentType(str, Enum):
    GST = "GST"
    UDYAM = "UDYAM"
    PAN = "PAN"
    EPFO = "EPFO"
    ESIC = "ESIC"
    OEM = "OEM"
    DIGILOCKER = "DIGILOCKER"
    BLACKLIST = "BLACKLIST"
    UNKNOWN = "UNKNOWN"


class AuditAction(str, Enum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_PROCESSING_STARTED = "DOCUMENT_PROCESSING_STARTED"
    OCR_STARTED = "OCR_STARTED"
    OCR_COMPLETED = "OCR_COMPLETED"
    FACTS_EXTRACTED = "FACTS_EXTRACTED"
    SOURCE_VERIFICATION_STARTED = "SOURCE_VERIFICATION_STARTED"
    SOURCE_VERIFICATION_COMPLETED = "SOURCE_VERIFICATION_COMPLETED"
    RULE_EVALUATED = "RULE_EVALUATED"
    SCORE_CALCULATED = "SCORE_CALCULATED"
    RISK_CALCULATED = "RISK_CALCULATED"
    AI_RECOMMENDATION_GENERATED = "AI_RECOMMENDATION_GENERATED"
    AI_CHAT_USED = "AI_CHAT_USED"
    DECISION_SUBMITTED = "DECISION_SUBMITTED"
    VERIFICATION_RETRIED = "VERIFICATION_RETRIED"
